version: "3.9"
services:
  api-cotizaciones:
    build: api-cotizaciones
    ports:
      - "3000:3000"
  api-proxy-db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
