name: Integracion Continua
on: [push]
jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Listar Versiones
        run: |
          npm -v
          node -v
          docker -v
          ls -la
      - name: Instalacion Dependencias
        run: |
          cd api-cotizaciones
          npm install
      - name: Aplicar Linting
        run: |
          cd api-cotizaciones
          npm run lint
      - name: Ejecutar Pruebas Unitarias
        run: |
          cd api-cotizaciones
          npm run test
      - name: Generar Transpilacion
        run: |
          cd api-cotizaciones
          npm run build
